import { z } from 'zod'
import { DeviceSelectionTraceV1Schema } from './art-director-v1.js'
import { StudioSeriesSchema } from './series.js'

export const JOB_SCHEMA_VERSION_V2 = 2 as const
export const VISUAL_CONTRACT_VERSION_V1 = 1 as const
export const Sha256V1Schema = z.string().regex(/^[a-f0-9]{64}$/)
export const IdentifierV1Schema = z.string().regex(/^[a-z0-9][a-z0-9_-]{1,95}$/i)
export const SeriesV2Schema = StudioSeriesSchema
export type SeriesV2 = z.infer<typeof SeriesV2Schema>
export const SourceModeV2Schema = z.enum(['extract', 'solo', 'short_native'])
export type SourceModeV2 = z.infer<typeof SourceModeV2Schema>
export const VideoPlatformV1Schema = z.enum(['youtube_shorts', 'linkedin', 'tiktok', 'instagram_reels'])
export type VideoPlatformV1 = z.infer<typeof VideoPlatformV1Schema>
export const TreatmentLaneV1Schema = z.enum(['restrained', 'premium', 'experimental'])
export type TreatmentLaneV1 = z.infer<typeof TreatmentLaneV1Schema>

export const StageNameV2Schema = z.enum(['brief','script','recording_brief','ingest','normalize','transcript','source_analysis','candidates','claims','visual_plan','assets','styleframes','animatic','treatment','render','qa','package'])
export type StageNameV2 = z.infer<typeof StageNameV2Schema>
export const ApprovalGateV2Schema = z.enum(['angle','evidence','visual_plan','storyboard','animatic','treatment','final','package'])
export type ApprovalGateV2 = z.infer<typeof ApprovalGateV2Schema>

export const NormalizedPointV1Schema = z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1), z: z.number().optional() }).strict()
export const NormalizedRectV1Schema = z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1), width: z.number().positive().max(1), height: z.number().positive().max(1) }).strict().superRefine((v,c) => {
  if (v.x + v.width > 1.000001) c.addIssue({ code:'custom', path:['width'], message:'rectangle exceeds normalized width' })
  if (v.y + v.height > 1.000001) c.addIssue({ code:'custom', path:['height'], message:'rectangle exceeds normalized height' })
})
export type NormalizedRectV1 = z.infer<typeof NormalizedRectV1Schema>

export const SourceSyncV1Schema = z.object({ strategy:z.enum(['embedded_timecode','audio_waveform','manual_offset','already_mixed']), offset_ms:z.number().int(), confidence:z.number().min(0).max(1).optional(), reference_source_id:IdentifierV1Schema.optional() }).strict()
export const ParticipantReferenceV1Schema = z.discriminatedUnion('kind', [
  z.object({ kind:z.literal('krish_profile'), profile_id:IdentifierV1Schema, version_hash:Sha256V1Schema, display_name:z.literal('Krish') }).strict(),
  z.object({ kind:z.literal('job_local'), label:z.string().trim().min(1).max(80), consent_ref:z.string().trim().min(1) }).strict(),
])
export type ParticipantReferenceV1 = z.infer<typeof ParticipantReferenceV1Schema>

const participantReferenceKey = (participant: ParticipantReferenceV1): string => participant.kind === 'krish_profile'
  ? `krish_profile:${participant.profile_id.toLowerCase()}`
  : `job_local:${participant.consent_ref.toLowerCase()}`

export const MediaSourceV1Schema = z.object({
  source_id:IdentifierV1Schema, kind:z.enum(['video','audio','screen_recording']), role:z.enum(['primary_camera','secondary_camera','guest_camera','mixed_program','isolated_audio','screen_recording','reference']), ref:z.string().min(1), content_hash:Sha256V1Schema.optional(), rights:z.enum(['owned','permissioned','commentary_exception','unverified']).default('unverified'), consent_ref:z.string().min(1).optional(), participant:ParticipantReferenceV1Schema.optional(), participants:z.array(ParticipantReferenceV1Schema).max(32).optional(), attribution:z.string().min(1).optional(),rights_rationale:z.string().min(20).optional(),editorial_purpose:z.string().min(20).optional(),sync:SourceSyncV1Schema, include_in_edit:z.boolean().default(true),
}).strict().superRefine((v,c) => {
  if (['primary_camera','secondary_camera','guest_camera','mixed_program'].includes(v.role) && v.kind !== 'video') c.addIssue({ code:'custom', path:['kind'], message:`${v.role} must be video` })
  if (v.role === 'isolated_audio' && v.kind !== 'audio') c.addIssue({ code:'custom', path:['kind'], message:'isolated_audio must be audio' })
  if (v.role === 'screen_recording' && v.kind !== 'screen_recording') c.addIssue({ code:'custom', path:['kind'], message:'screen_recording role requires screen_recording kind' })
  if (v.rights === 'commentary_exception' && (!v.attribution || !v.rights_rationale || !v.editorial_purpose)) c.addIssue({ code:'custom', path:['rights'], message:'commentary-exception sources require attribution, a rights rationale, and a recorded editorial purpose' })
  if (v.participant && v.participants?.length) c.addIssue({ code:'custom', path:['participants'], message:'use canonical participants[] or the legacy singular participant, never both' })
  const roster=v.participants?.length?v.participants:(v.participant?[v.participant]:[])
  if (new Set(roster.map(participantReferenceKey)).size!==roster.length) c.addIssue({ code:'custom', path:['participants'], message:'participant roster contains duplicate declarations' })
  if (v.include_in_edit&&v.role==='guest_camera'&&!roster.some(participant=>participant.kind==='job_local')) c.addIssue({ code:'custom', path:['participants'], message:'included guest_camera sources require a consented job-local participant roster' })
  if (v.include_in_edit&&v.role==='mixed_program'&&!roster.length) c.addIssue({ code:'custom', path:['participants'], message:'included mixed_program sources require a participant roster' })
})
export type MediaSourceV1 = z.infer<typeof MediaSourceV1Schema>
export function mediaSourceParticipantRoster(source: Pick<MediaSourceV1, 'participant' | 'participants'>): ParticipantReferenceV1[] {
  return source.participants?.length ? source.participants : source.participant ? [source.participant] : []
}
export const SourceSidecarV1Schema = z.object({
  sidecar_id:IdentifierV1Schema,
  source_id:IdentifierV1Schema,
  kind:z.enum(['captions','edit_decisions']),
  format:z.enum(['srt','vtt','edl','fcpxml']),
  ref:z.string().min(1),
  content_hash:Sha256V1Schema,
}).strict().superRefine((value,context)=>{
  if (value.kind==='captions'&&!['srt','vtt'].includes(value.format)) context.addIssue({ code:'custom', path:['format'], message:'caption sidecars must use SRT or VTT' })
  if (value.kind==='edit_decisions'&&!['edl','fcpxml'].includes(value.format)) context.addIssue({ code:'custom', path:['format'], message:'edit-decision sidecars must use EDL or FCPXML' })
})
export type SourceSidecarV1 = z.infer<typeof SourceSidecarV1Schema>

export const SourceBundleV1Schema = z.object({ schema_version:z.literal(1), bundle_id:IdentifierV1Schema, primary_source_id:IdentifierV1Schema, sources:z.array(MediaSourceV1Schema).min(1).max(32), sidecars:z.array(SourceSidecarV1Schema).max(32).optional(), intake_provenance:z.object({candidate_id:z.string().regex(/^intake_[a-f0-9]{24}$/),candidate_hash:Sha256V1Schema,review_id:z.string().uuid(),review_hash:Sha256V1Schema,inbox_fingerprint:Sha256V1Schema,discovery_event_hash:Sha256V1Schema,media_hashes:z.array(Sha256V1Schema).min(1).max(32),sidecar_hashes:z.array(Sha256V1Schema).max(32),verified_at:z.string().datetime()}).strict().optional() }).strict().superRefine((v,c) => {
  const ids=v.sources.map(x=>x.source_id)
  if (new Set(ids).size !== ids.length) c.addIssue({ code:'custom', path:['sources'], message:'source IDs must be unique' })
  const primary=v.sources.find(x=>x.source_id===v.primary_source_id)
  if (!primary) c.addIssue({ code:'custom', path:['primary_source_id'], message:'primary source must exist' })
  else if (primary.kind==='audio') c.addIssue({ code:'custom', path:['primary_source_id'], message:'primary source must contain video' })
  v.sources.forEach((x,i)=>{ if(x.sync.reference_source_id && !ids.includes(x.sync.reference_source_id)) c.addIssue({ code:'custom', path:['sources',i,'sync','reference_source_id'], message:'sync reference must exist' }) })
  const sidecarIds=(v.sidecars??[]).map(sidecar=>sidecar.sidecar_id)
  if (new Set(sidecarIds).size!==sidecarIds.length) c.addIssue({ code:'custom', path:['sidecars'], message:'sidecar IDs must be unique' })
  ;(v.sidecars??[]).forEach((sidecar,index)=>{ if(!ids.includes(sidecar.source_id)) c.addIssue({ code:'custom', path:['sidecars',index,'source_id'], message:'sidecar source must exist' }) })
  if (v.intake_provenance) {
    const sourceHashes=v.sources.map(source=>source.content_hash)
    if (sourceHashes.some(hash=>!hash)) c.addIssue({ code:'custom', path:['sources'], message:'Drive intake source bundles require a content hash for every source' })
    const declared=[...v.intake_provenance.media_hashes].sort()
    const actual=sourceHashes.filter((hash):hash is string=>Boolean(hash)).sort()
    if (JSON.stringify(declared)!==JSON.stringify(actual)) c.addIssue({ code:'custom', path:['intake_provenance','media_hashes'], message:'Drive intake provenance media hashes must exactly match source content hashes' })
    const declaredSidecars=[...v.intake_provenance.sidecar_hashes].sort()
    const actualSidecars=(v.sidecars??[]).map(sidecar=>sidecar.content_hash).sort()
    if (JSON.stringify(declaredSidecars)!==JSON.stringify(actualSidecars)) c.addIssue({ code:'custom', path:['intake_provenance','sidecar_hashes'], message:'Drive intake provenance sidecar hashes must exactly match typed sidecars' })
  }
})
export type SourceBundleV1 = z.infer<typeof SourceBundleV1Schema>

export const StageStateV2Schema = z.object({ status:z.enum(['pending','running','complete','blocked','invalidated','skipped']), artifact_hash:Sha256V1Schema.optional(), artifact_path:z.string().min(1).optional(), updated_at:z.string().min(1), reason:z.string().min(1).optional() }).strict()
export const ApprovalV2Schema = z.object({ gate:ApprovalGateV2Schema, decision:z.enum(['approved','rejected','override']), artifact_hash:Sha256V1Schema, reason:z.string().min(1).optional(), actor:z.enum(['krish','codex','system']).default('krish'), confirmation_ref:z.string().min(12).max(800).optional(), occurred_at:z.string().min(1) }).strict().superRefine((v,c)=>{ if(v.decision==='override'&&!v.reason?.trim()) c.addIssue({code:'custom',path:['reason'],message:'override requires a reason'}) })
export const JobManifestV2Schema = z.object({
  schema_version:z.literal(JOB_SCHEMA_VERSION_V2), job_id:IdentifierV1Schema, created_at:z.string().min(1), updated_at:z.string().min(1), series:SeriesV2Schema, mode:SourceModeV2Schema, purpose:z.enum(['production','calibration']).default('production'), presenter_name:z.literal('Krish').optional(), source_bundle:SourceBundleV1Schema.optional(), target_platforms:z.array(VideoPlatformV1Schema).min(1).max(4).refine(v=>new Set(v).size===v.length,{message:'target platforms must be unique'}), treatment_lane:TreatmentLaneV1Schema, identity_profile:z.object({profile_id:IdentifierV1Schema,version_hash:Sha256V1Schema,display_name:z.literal('Krish')}).strict().optional(), consent_refs:z.array(z.string().min(1)).default([]), config_hash:Sha256V1Schema, skill_hashes:z.record(z.string(),Sha256V1Schema), pinned_inputs:z.object({config_path:z.string().min(1),skill_paths:z.record(z.string(),z.string().min(1)),technique_registry_path:z.string().min(1).optional(),technique_registry_hash:Sha256V1Schema.optional()}).strict(), stages:z.record(StageNameV2Schema,StageStateV2Schema), approvals:z.array(ApprovalV2Schema), review_decision_hashes:z.array(Sha256V1Schema).default([]),
}).strict().superRefine((v,c)=>{if(v.mode!=='short_native'&&!v.source_bundle)c.addIssue({code:'custom',path:['source_bundle'],message:'extract and solo jobs require a source bundle at creation'})})
export type JobManifestV2 = z.infer<typeof JobManifestV2Schema>
export const StudioEventV2Schema = z.object({ schema_version:z.literal(2), event_id:z.string().uuid(), job_id:IdentifierV1Schema, type:z.enum(['job_created','source_bundle_attached','stage_started','stage_completed','stage_invalidated','stage_blocked','approval_recorded','feedback_recorded','rule_promoted','capability_downgraded','asset_approved','identity_enrolled','identity_revoked','magic_edit_intent_received','magic_edit_candidate_created','magic_edit_activated','review_decision_recorded','review_recovery_recorded']), occurred_at:z.string().min(1), payload:z.record(z.string(),z.unknown()) }).strict()
export type StudioEventV2 = z.infer<typeof StudioEventV2Schema>

export const FeedbackScopeV2Schema=z.object({level:z.enum(['global','series','mode','treatment','platform','job']),key:z.string().min(1)}).strict()
export const FeedbackEventV2Schema=z.object({schema_version:z.literal(2),feedback_id:z.string().uuid(),job_id:IdentifierV1Schema,artifact_id:z.string().min(1),artifact_kind:z.enum(['script','candidate','caption','visual_plan','asset','styleframe','animatic','treatment','render','copy','external_final','approval']),stage:StageNameV2Schema,action:z.enum(['accept','reject','revise','praise']),origin:z.enum(['user','codex','system']).default('user'),evidence_class:z.literal('taste'),before_hash:Sha256V1Schema,after_hash:Sha256V1Schema.optional(),delta_features:z.array(z.object({feature:z.string().min(1),before:z.unknown().optional(),after:z.unknown().optional()}).strict()),user_note:z.string().min(1).optional(),inferred_rationale:z.string().min(1),confidence:z.number().min(0).max(1),scope:FeedbackScopeV2Schema,confirmation:z.enum(['pending','confirmed','corrected','observation_only']),occurred_at:z.string().min(1),exact_external_final:z.boolean().default(false)}).strict().superRefine((v,c)=>{if(v.exact_external_final&&v.artifact_kind!=='external_final')c.addIssue({code:'custom',path:['artifact_kind'],message:'exact external final flag requires external_final kind'});if(v.origin!=='user'&&v.confirmation!=='observation_only')c.addIssue({code:'custom',path:['confirmation'],message:'non-user feedback can only be an observation'})})
export type FeedbackEventV2=z.infer<typeof FeedbackEventV2Schema>
export const FeedbackConfirmationV2Schema = z.object({
  schema_version: z.literal(2),
  confirmation_id: z.string().uuid(),
  feedback_id: z.string().uuid(),
  job_id: IdentifierV1Schema,
  event_hash: Sha256V1Schema,
  confirmation: z.enum(['confirmed', 'corrected']),
  confirmed_rationale: z.string().min(1),
  confirmation_ref: z.string().min(12).max(800),
  confirmed_at: z.string().min(1),
}).strict().superRefine((value, context) => {
  const legacyPrefix = `codex-user-confirmation:feedback:${value.event_hash}:`
  const portablePrefix = /^studio-user-confirmation:(?:control_center|codex_desktop|codex_cli|codex_cloud|claude_desktop|claude_code|claude_ai|chatgpt|other_mcp):feedback:[a-f0-9]{64}:/
  const portableMatch = value.confirmation_ref.match(portablePrefix)?.[0]
  const portableHash = portableMatch?.split(':')[3]
  const legacyValid = value.confirmation_ref.startsWith(legacyPrefix) && Boolean(value.confirmation_ref.slice(legacyPrefix.length).trim())
  const portableValid = portableHash === value.event_hash && Boolean(portableMatch && value.confirmation_ref.slice(portableMatch.length).trim())
  if (!legacyValid && !portableValid) {
    context.addIssue({ code: 'custom', path: ['confirmation_ref'], message: 'feedback confirmation requires an event-bound user receipt from a supported studio client' })
  }
})
export type FeedbackConfirmationV2 = z.infer<typeof FeedbackConfirmationV2Schema>

export const TimedRectKeyframeV1Schema = z.object({ at_ms:z.number().int().nonnegative(), bounds:NormalizedRectV1Schema, confidence:z.number().min(0).max(1) }).strict()
export const HandRectKeyframeV1Schema = TimedRectKeyframeV1Schema.extend({ hand:z.enum(['left','right','unknown']) }).strict()
export const AnalyzedSourceV1Schema = z.object({ source_id:IdentifierV1Schema, source_hash:Sha256V1Schema, duration_ms:z.number().int().positive(), width:z.number().int().positive(), height:z.number().int().positive(), fps:z.number().positive(), audio_hz:z.number().int().positive().nullable(), canonical_offset_ms:z.number().int() }).strict()
export const ShotBoundaryV1Schema = z.object({ shot_id:IdentifierV1Schema, source_id:IdentifierV1Schema, start_ms:z.number().int().nonnegative(), end_ms:z.number().int().positive(), transition:z.enum(['source_start','hard_cut','dissolve','fade','camera_stop','unknown']), confidence:z.number().min(0).max(1) }).strict().refine(v=>v.end_ms>v.start_ms,{message:'shot must end after it starts'})
export const SubjectTrackV1Schema = z.object({ track_id:IdentifierV1Schema, source_id:IdentifierV1Schema, role:z.enum(['krish','guest','unknown']), profile_id:IdentifierV1Schema.optional(), profile_version_hash:Sha256V1Schema.optional(), start_ms:z.number().int().nonnegative(), end_ms:z.number().int().positive(), face_keyframes:z.array(TimedRectKeyframeV1Schema), body_keyframes:z.array(TimedRectKeyframeV1Schema), hand_keyframes:z.array(HandRectKeyframeV1Schema), detection_confidence:z.number().min(0).max(1) }).strict().superRefine((v,c)=>{
  if(v.end_ms<=v.start_ms)c.addIssue({code:'custom',path:['end_ms'],message:'subject track must end after start'})
  if(v.role==='krish'&&(!v.profile_id||!v.profile_version_hash))c.addIssue({code:'custom',path:['profile_id'],message:'Krish track requires enrolled profile provenance'})
  if(v.role!=='krish'&&(v.profile_id||v.profile_version_hash))c.addIssue({code:'custom',path:['profile_id'],message:'guest identities must remain job-local'})
  ;(['face_keyframes','body_keyframes','hand_keyframes'] as const).forEach(k=>v[k].forEach((x,i)=>{if(x.at_ms<v.start_ms||x.at_ms>v.end_ms)c.addIssue({code:'custom',path:[k,i,'at_ms'],message:'keyframe outside subject track'})}))
})
export const ActiveSpeakerIntervalV1Schema = z.object({ interval_id:IdentifierV1Schema, source_id:IdentifierV1Schema, track_id:IdentifierV1Schema.optional(), speaker_label:z.string().min(1).max(80), start_ms:z.number().int().nonnegative(), end_ms:z.number().int().positive(), overlap:z.boolean().default(false), confidence:z.number().min(0).max(1) }).strict().refine(v=>v.end_ms>v.start_ms,{message:'speaker interval must end after start'})
export const GestureTargetV1Schema = z.discriminatedUnion('kind',[z.object({kind:z.literal('point'),point:NormalizedPointV1Schema}).strict(),z.object({kind:z.literal('track'),target_id:IdentifierV1Schema}).strict(),z.object({kind:z.literal('region'),target_id:IdentifierV1Schema}).strict(),z.object({kind:z.literal('direction'),direction:z.enum(['left','right','up','down','camera'])}).strict()])
export const GestureIntervalV1Schema = z.object({ gesture_id:IdentifierV1Schema, track_id:IdentifierV1Schema, start_ms:z.number().int().nonnegative(), end_ms:z.number().int().positive(), hand:z.enum(['left','right','both','unknown']), kind:z.enum(['point','present','draw','hold','count','open_palm','emphasis','other']), direction:z.enum(['left','right','up','down','camera','unknown']).optional(), target:GestureTargetV1Schema.optional(), confidence:z.number().min(0).max(1) }).strict().refine(v=>v.end_ms>v.start_ms,{message:'gesture must end after start'})
export const GazeIntervalV1Schema = z.object({ gaze_id:IdentifierV1Schema, track_id:IdentifierV1Schema, start_ms:z.number().int().nonnegative(), end_ms:z.number().int().positive(), direction:z.enum(['camera','left','right','up','down','other_subject','object','unknown']), target_id:IdentifierV1Schema.optional(), confidence:z.number().min(0).max(1) }).strict().refine(v=>v.end_ms>v.start_ms,{message:'gaze must end after start'})
export const TimedRegionV1Schema = z.object({ region_id:IdentifierV1Schema, source_id:IdentifierV1Schema, start_ms:z.number().int().nonnegative(), end_ms:z.number().int().positive(), bounds:NormalizedRectV1Schema, reason:z.string().min(8), confidence:z.number().min(0).max(1) }).strict().refine(v=>v.end_ms>v.start_ms,{message:'region must end after start'})
export const AnalysisSidecarV1Schema = z.object({ sidecar_id:IdentifierV1Schema, kind:z.enum(['mask','depth','landmarks','optical_flow','speaker_embeddings']), source_id:IdentifierV1Schema, path:z.string().min(1), sha256:Sha256V1Schema, start_ms:z.number().int().nonnegative().optional(), end_ms:z.number().int().positive().optional() }).strict()
export const SourceQualityIssueV1Schema = z.object({ issue_id:IdentifierV1Schema, source_id:IdentifierV1Schema, kind:z.enum(['blur','noise','underexposure','overexposure','occlusion','dropped_frames','audio_drift','tracking_loss','identity_ambiguity','speaker_ambiguity','other']), severity:z.enum(['info','warn','block']), detail:z.string().min(8), start_ms:z.number().int().nonnegative().optional(), end_ms:z.number().int().positive().optional() }).strict()
const unique=(xs:string[])=>new Set(xs).size===xs.length
export const SourceVisualAnalysisV1Schema = z.object({ schema_version:z.literal(1), analysis_id:IdentifierV1Schema, job_id:IdentifierV1Schema, source_bundle_hash:Sha256V1Schema, coordinate_space:z.literal('normalized_0_1'), timebase:z.literal('source_local_ms'), generated_at:z.string().min(1), capabilities:z.object({tier:z.union([z.literal(1),z.literal(2),z.literal(3)]),analyzers:z.record(z.string(),z.string().min(1)),unavailable:z.array(z.string().min(1)).default([]),fallbacks:z.array(z.string().min(1)).default([])}).strict(), sources:z.array(AnalyzedSourceV1Schema).min(1).max(32), shots:z.array(ShotBoundaryV1Schema), subjects:z.array(SubjectTrackV1Schema), active_speakers:z.array(ActiveSpeakerIntervalV1Schema), gestures:z.array(GestureIntervalV1Schema), gaze:z.array(GazeIntervalV1Schema), negative_space:z.array(TimedRegionV1Schema), protected_regions:z.array(TimedRegionV1Schema), sidecars:z.array(AnalysisSidecarV1Schema), quality_issues:z.array(SourceQualityIssueV1Schema) }).strict().superRefine((v,c)=>{
  const sources=new Map(v.sources.map(x=>[x.source_id,x])); const tracks=new Map(v.subjects.map(x=>[x.track_id,x]))
  if(!unique(v.sources.map(x=>x.source_id)))c.addIssue({code:'custom',path:['sources'],message:'source IDs must be unique'})
  if(!unique(v.shots.map(x=>x.shot_id)))c.addIssue({code:'custom',path:['shots'],message:'shot IDs must be unique'})
  if(!unique(v.subjects.map(x=>x.track_id)))c.addIssue({code:'custom',path:['subjects'],message:'track IDs must be unique'})
  ;([['shots',v.shots],['active_speakers',v.active_speakers],['negative_space',v.negative_space],['protected_regions',v.protected_regions]] as const).forEach(([k,xs])=>xs.forEach((x,i)=>{const s=sources.get(x.source_id);if(!s)c.addIssue({code:'custom',path:[k,i,'source_id'],message:'unknown source'});else if(x.end_ms>s.duration_ms)c.addIssue({code:'custom',path:[k,i,'end_ms'],message:'item exceeds source duration'})}))
  v.subjects.forEach((x,i)=>{const s=sources.get(x.source_id);if(!s)c.addIssue({code:'custom',path:['subjects',i,'source_id'],message:'unknown source'});else if(x.end_ms>s.duration_ms)c.addIssue({code:'custom',path:['subjects',i,'end_ms'],message:'track exceeds source duration'})})
  v.active_speakers.forEach((x,i)=>{if(x.track_id&&!tracks.has(x.track_id))c.addIssue({code:'custom',path:['active_speakers',i,'track_id'],message:'unknown subject track'})})
  v.gestures.forEach((x,i)=>{const t=tracks.get(x.track_id);if(!t)c.addIssue({code:'custom',path:['gestures',i,'track_id'],message:'unknown subject track'});else if(x.start_ms<t.start_ms||x.end_ms>t.end_ms)c.addIssue({code:'custom',path:['gestures',i],message:'gesture outside track'})})
  v.gaze.forEach((x,i)=>{const t=tracks.get(x.track_id);if(!t)c.addIssue({code:'custom',path:['gaze',i,'track_id'],message:'unknown subject track'});else if(x.start_ms<t.start_ms||x.end_ms>t.end_ms)c.addIssue({code:'custom',path:['gaze',i],message:'gaze outside track'})})
  ;([...v.sidecars,...v.quality_issues]).forEach((x,i)=>{if(!sources.has(x.source_id))c.addIssue({code:'custom',path:['sidecars_or_quality',i,'source_id'],message:'unknown source'})})
})
export type SourceVisualAnalysisV1 = z.infer<typeof SourceVisualAnalysisV1Schema>

export const AttentionTargetV1Schema = z.object({ kind:z.enum(['presenter','guest','evidence','owned_artifact','sketch','generated_illustration','screen','environment','typography','negative_space','none']), target_id:IdentifierV1Schema.optional() }).strict().superRefine((v,c)=>{if(['guest','evidence','owned_artifact','sketch','generated_illustration','screen'].includes(v.kind)&&!v.target_id)c.addIssue({code:'custom',path:['target_id'],message:`${v.kind} requires a target ID`})})
export type AttentionTargetV1 = z.infer<typeof AttentionTargetV1Schema>
export const NarrativeBeatV1Schema = z.object({ beat_id:IdentifierV1Schema,start_ms:z.number().int().nonnegative(),end_ms:z.number().int().positive(),transcript:z.string(),source_spans:z.array(z.object({source_id:IdentifierV1Schema,start_ms:z.number().int().nonnegative(),end_ms:z.number().int().positive()}).strict().refine(v=>v.end_ms>v.start_ms,{message:'source span must end after start'})),claim_ids:z.array(IdentifierV1Schema).default([]),narrative_function:z.enum(['hook','context','tension','evidence','mechanism','turn','reset','payoff','ending']),viewer_task:z.enum(['connect_with_speaker','understand_mechanism','verify_evidence','inspect_artifact','locate_story','feel_stakes','reset_attention','land_payoff']),emotional_function:z.enum(['curiosity','trust','tension','surprise','urgency','delight','relief','reflection']),visual_density:z.enum(['rest','low','medium','high']),proof_dependency:z.boolean(),primary_attention_target:AttentionTargetV1Schema,rationale:z.string().min(12),opens_question:z.boolean().default(false),answers_beat_id:IdentifierV1Schema.optional() }).strict().refine(v=>v.end_ms>v.start_ms,{message:'beat must end after start'}).refine(v=>v.answers_beat_id!==v.beat_id,{message:'a beat cannot answer its own question',path:['answers_beat_id']})
export type NarrativeBeatV1 = z.infer<typeof NarrativeBeatV1Schema>

export const AssetTruthRoleV1Schema=z.enum(['evidence','owned_artifact','illustration','decoration'])
export const VisualAssetKindV1Schema=z.enum(['evidence_screenshot','document','screen_recording','chart','map','archive','licensed_b_roll','owned_sketch','owned_photo','generated_still','generated_video','interface_capture'])
export const VisualAssetV1Schema=z.object({asset_id:IdentifierV1Schema,media_kind:z.enum(['image','video','document']),content_kind:VisualAssetKindV1Schema,truth_role:AssetTruthRoleV1Schema,path:z.string().min(1),sha256:Sha256V1Schema,source_url:z.string().url().optional(),rights:z.enum(['owned','permissioned','licensed','third_party_commentary_excerpt','generated','unverified']),attribution:z.string().min(1).optional(),rights_rationale:z.string().min(12),generated:z.boolean(),label:z.string().min(1).optional(),approval:z.object({state:z.enum(['unreviewed','approved','rejected']),approved_by:z.literal('Krish').optional(),approved_at:z.string().min(1).optional(),artifact_hash:Sha256V1Schema.optional()}).strict()}).strict().superRefine((v,c)=>{
 const generatedKind=['generated_still','generated_video'].includes(v.content_kind);if(generatedKind!==v.generated)c.addIssue({code:'custom',path:['generated'],message:'generated flag must match asset kind'});if(v.generated&&v.truth_role==='evidence')c.addIssue({code:'custom',path:['truth_role'],message:'generated media cannot be evidence'});if(v.generated&&!v.label)c.addIssue({code:'custom',path:['label'],message:'generated media requires an illustration label'});if(v.truth_role==='evidence'&&(!v.source_url||!v.attribution))c.addIssue({code:'custom',path:['source_url'],message:'evidence requires URL and attribution'});if(v.approval.state==='approved'&&(!v.approval.approved_by||!v.approval.approved_at||!v.approval.artifact_hash))c.addIssue({code:'custom',path:['approval'],message:'approved asset requires exact Krish approval provenance'})
})
export type VisualAssetV1=z.infer<typeof VisualAssetV1Schema>
export const VisualAssetRequirementV1Schema=z.object({asset_id:IdentifierV1Schema,content_kind:VisualAssetKindV1Schema,truth_role:AssetTruthRoleV1Schema,narrative_job:z.enum(['prove','explain','orient','compare','evoke','delight']),claim_ids:z.array(IdentifierV1Schema).default([]),brief:z.string().min(12),generated_allowed:z.boolean().default(false),required:z.boolean().default(true),fallback:z.string().min(8)}).strict().superRefine((v,c)=>{if(v.truth_role==='evidence'&&v.generated_allowed)c.addIssue({code:'custom',path:['generated_allowed'],message:'evidence cannot allow generation'})})

export const CameraKeyframeV1Schema=z.object({at_ms:z.number().int().nonnegative(),crop:NormalizedRectV1Schema,zoom:z.number().min(1).max(4),rotation_degrees:z.number().min(-10).max(10).default(0),confidence:z.number().min(0).max(1)}).strict()
export type CameraKeyframeV1=z.infer<typeof CameraKeyframeV1Schema>
export const CameraPlanV1Schema=z.object({camera_plan_id:IdentifierV1Schema,source_id:IdentifierV1Schema,subject_track_ids:z.array(IdentifierV1Schema),start_ms:z.number().int().nonnegative(),end_ms:z.number().int().positive(),framing:z.enum(['wide','medium','medium_close','close','extreme_close','two_shot','split','insert']),movement:z.enum(['locked','reframe','follow','push','pull','pan','tilt','whip','dolly_zoom']),lead_room:z.enum(['auto','left','right','up','down','none']).default('auto'),gesture_anchor_id:IdentifierV1Schema.optional(),protected_region_ids:z.array(IdentifierV1Schema).default([]),keyframes:z.array(CameraKeyframeV1Schema).min(1),easing:z.enum(['linear','ease_in','ease_out','ease_in_out','spring','hold']),max_velocity:z.number().positive(),max_acceleration:z.number().positive(),minimum_hold_ms:z.number().int().nonnegative(),quality_floor:z.object({minimum_effective_width_px:z.number().int().positive(),allow_upscale:z.boolean().default(false)}).strict(),confidence:z.number().min(0).max(1),fallback:z.string().min(8)}).strict().superRefine((v,c)=>{if(v.end_ms<=v.start_ms)c.addIssue({code:'custom',path:['end_ms'],message:'camera plan must end after start'});let p=-1;v.keyframes.forEach((x,i)=>{if(x.at_ms<v.start_ms||x.at_ms>v.end_ms)c.addIssue({code:'custom',path:['keyframes',i,'at_ms'],message:'keyframe outside camera plan'});if(x.at_ms<p)c.addIssue({code:'custom',path:['keyframes',i,'at_ms'],message:'keyframes must be ordered'});p=x.at_ms})})
export type CameraPlanV1=z.infer<typeof CameraPlanV1Schema>
export const LayerDirectiveV1Schema=z.object({layer_id:IdentifierV1Schema,z_index:z.number().int(),kind:z.enum(['source','subject_cutout','asset','caption','branding','annotation','background']),target_id:IdentifierV1Schema.optional(),anchor:z.enum(['full','top_left','top_right','left','right','center','bottom','gesture','tracked_region']),bounds:NormalizedRectV1Schema.optional(),tracking_keyframes:z.array(TimedRectKeyframeV1Schema).min(2).optional(),opacity:z.number().min(0).max(1).default(1),blend_mode:z.enum(['normal','multiply','screen','overlay']).default('normal'),protected:z.boolean().default(false),visible_start_ms:z.number().int().nonnegative().optional(),visible_end_ms:z.number().int().positive().optional()}).strict().superRefine((v,c)=>{if(['source','subject_cutout','asset'].includes(v.kind)&&!v.target_id)c.addIssue({code:'custom',path:['target_id'],message:`${v.kind} layer requires a target ID`});if((v.visible_start_ms===undefined)!==(v.visible_end_ms===undefined))c.addIssue({code:'custom',path:['visible_start_ms'],message:'layer visibility requires both bounds'});if(v.visible_start_ms!==undefined&&v.visible_end_ms!==undefined&&v.visible_end_ms<=v.visible_start_ms)c.addIssue({code:'custom',path:['visible_end_ms'],message:'layer visibility must end after it starts'});if(v.tracking_keyframes&&v.anchor!=='tracked_region')c.addIssue({code:'custom',path:['anchor'],message:'tracking keyframes require the tracked_region anchor'});v.tracking_keyframes?.forEach((frame,index)=>{if(index>0&&frame.at_ms<=v.tracking_keyframes![index-1]!.at_ms)c.addIssue({code:'custom',path:['tracking_keyframes',index,'at_ms'],message:'tracking keyframes must be strictly ordered'})})})
export const ShotDirectiveV1Schema=z.object({shot_id:IdentifierV1Schema,beat_id:IdentifierV1Schema,start_ms:z.number().int().nonnegative(),end_ms:z.number().int().positive(),source_id:IdentifierV1Schema,source_start_ms:z.number().int().nonnegative(),source_end_ms:z.number().int().positive(),subject_track_ids:z.array(IdentifierV1Schema),primary_attention_target:AttentionTargetV1Schema,technique_ids:z.array(IdentifierV1Schema),camera_plan:CameraPlanV1Schema,layers:z.array(LayerDirectiveV1Schema).min(1),transition_in:z.enum(['cut','match_cut','smash_cut','dissolve','fade','whip','portal','none']),transition_out:z.enum(['cut','match_cut','smash_cut','dissolve','fade','whip','portal','none']),audio_continuity:z.enum(['direct','j_cut','l_cut','sound_bridge','room_tone']),rationale:z.string().min(12)}).strict().superRefine((v,c)=>{if(v.end_ms<=v.start_ms)c.addIssue({code:'custom',path:['end_ms'],message:'shot must end after start'});if(v.source_end_ms<=v.source_start_ms)c.addIssue({code:'custom',path:['source_end_ms'],message:'source span must end after it starts'});if(Math.abs((v.end_ms-v.start_ms)-(v.source_end_ms-v.source_start_ms))>34)c.addIssue({code:'custom',path:['source_end_ms'],message:'source and output shot durations must match within one frame'});if(v.camera_plan.start_ms>v.start_ms||v.camera_plan.end_ms<v.end_ms)c.addIssue({code:'custom',path:['camera_plan'],message:'camera plan must cover shot'});if(v.camera_plan.source_id!==v.source_id)c.addIssue({code:'custom',path:['camera_plan','source_id'],message:'camera and shot source must match'});if(!unique(v.layers.map(x=>x.layer_id)))c.addIssue({code:'custom',path:['layers'],message:'layer IDs must be unique'});if(!unique(v.layers.map(x=>String(x.z_index))))c.addIssue({code:'custom',path:['layers'],message:'layer z-indexes must be unique'});v.layers.forEach((layer,index)=>{if(layer.visible_start_ms!==undefined&&layer.visible_end_ms!==undefined&&(layer.visible_start_ms<v.start_ms||layer.visible_end_ms>v.end_ms))c.addIssue({code:'custom',path:['layers',index,'visible_start_ms'],message:'layer visibility must remain inside its shot'});layer.tracking_keyframes?.forEach((frame,keyframeIndex)=>{if(frame.at_ms<v.start_ms||frame.at_ms>v.end_ms)c.addIssue({code:'custom',path:['layers',index,'tracking_keyframes',keyframeIndex,'at_ms'],message:'tracking keyframes must remain inside their shot'})})})})
export type ShotDirectiveV1=z.infer<typeof ShotDirectiveV1Schema>
export const DisclosureDecisionV1Schema=z.object({platform:VideoPlatformV1Schema,decision:z.enum(['required','not_required','pending']),rationale:z.string().min(12)}).strict()
export const VisualPlanEditorialReviewV1Schema=z.object({passed:z.boolean(),hard_blocks:z.array(z.string().min(1)),soft_blocks:z.array(z.string().min(1)),confidence_fallbacks:z.array(z.string().min(1)),experimental_techniques:z.array(IdentifierV1Schema),requires_styleframes:z.boolean(),requires_animatic:z.boolean()}).strict()

export const VisualNarrativePlanV1Schema=z.object({schema_version:z.literal(1),plan_id:IdentifierV1Schema,job_id:IdentifierV1Schema,candidate_id:IdentifierV1Schema,candidate_hash:Sha256V1Schema,claims_artifact_hash:Sha256V1Schema,source_analysis_artifact_hash:Sha256V1Schema,technique_registry_hash:Sha256V1Schema,preference_snapshot_hash:Sha256V1Schema,duration_ms:z.number().int().positive(),treatment_lane:TreatmentLaneV1Schema,beats:z.array(NarrativeBeatV1Schema).min(1),asset_requirements:z.array(VisualAssetRequirementV1Schema),resolved_assets:z.array(VisualAssetV1Schema).default([]),shot_directives:z.array(ShotDirectiveV1Schema).min(1),device_selection_traces:z.array(DeviceSelectionTraceV1Schema).default([]),budget:z.object({estimated_cost_gbp:z.number().nonnegative(),maximum_cost_gbp:z.number().nonnegative().default(15),exception_approved:z.boolean().default(false)}).strict(),disclosures:z.array(DisclosureDecisionV1Schema),fallbacks:z.array(z.object({trigger:z.string().min(8),action:z.string().min(8)}).strict()).default([]),strategy_summary:z.string().min(20),editorial_review:VisualPlanEditorialReviewV1Schema.optional()}).strict().superRefine((v,c)=>{
 const beatIds=v.beats.map(x=>x.beat_id),requiredAssetIds=v.asset_requirements.map(x=>x.asset_id),resolvedAssetIds=v.resolved_assets.map(x=>x.asset_id),assetIds=[...new Set([...requiredAssetIds,...resolvedAssetIds])],shotIds=v.shot_directives.map(x=>x.shot_id)
 if(!unique(beatIds))c.addIssue({code:'custom',path:['beats'],message:'beat IDs must be unique'});if(!unique(requiredAssetIds))c.addIssue({code:'custom',path:['asset_requirements'],message:'asset requirement IDs must be unique'});if(!unique(resolvedAssetIds))c.addIssue({code:'custom',path:['resolved_assets'],message:'resolved asset IDs must be unique'});if(!unique(shotIds))c.addIssue({code:'custom',path:['shot_directives'],message:'shot IDs must be unique'})
 let expected=0;v.beats.forEach((b,i)=>{if(Math.abs(b.start_ms-expected)>50)c.addIssue({code:'custom',path:['beats',i,'start_ms'],message:'beats must form a continuous ordered timeline'});if(b.end_ms>v.duration_ms)c.addIssue({code:'custom',path:['beats',i,'end_ms'],message:'beat exceeds duration'});expected=b.end_ms});if(Math.abs(expected-v.duration_ms)>50)c.addIssue({code:'custom',path:['beats'],message:'beats must cover full duration'})
 const last=v.beats.at(-1);if(last&&!['payoff','ending'].includes(last.narrative_function))c.addIssue({code:'custom',path:['beats',v.beats.length-1,'narrative_function'],message:'last beat must be payoff or ending'})
 const beatIndex=new Map(v.beats.map((b,i)=>[b.beat_id,i]));const answeredBeatIds=new Set<string>()
 v.beats.forEach((b,i)=>{if(!b.answers_beat_id)return;const opener=beatIndex.get(b.answers_beat_id);if(opener===undefined)c.addIssue({code:'custom',path:['beats',i,'answers_beat_id'],message:'unknown beat'});else if(opener>=i)c.addIssue({code:'custom',path:['beats',i,'answers_beat_id'],message:'a question must be answered by a later beat'});else if(!v.beats[opener]?.opens_question)c.addIssue({code:'custom',path:['beats',i,'answers_beat_id'],message:'the referenced beat does not open a question'});else answeredBeatIds.add(b.answers_beat_id)})
 const hookIndex=v.beats.reduce((latest,b,i)=>b.narrative_function==='hook'?i:latest,0)
 if(v.beats.length>1&&!v.beats.some((b,i)=>i>=hookIndex&&b.opens_question&&answeredBeatIds.has(b.beat_id)))c.addIssue({code:'custom',path:['beats'],message:'the hook must leave a question open that a later beat answers'})
 const beatSet=new Set(beatIds),assets=new Set(assetIds),shotBeats=new Set<string>();v.shot_directives.forEach((s,i)=>{const b=v.beats.find(x=>x.beat_id===s.beat_id);if(!beatSet.has(s.beat_id))c.addIssue({code:'custom',path:['shot_directives',i,'beat_id'],message:'unknown beat'});else if(b&&(s.start_ms<b.start_ms||s.end_ms>b.end_ms))c.addIssue({code:'custom',path:['shot_directives',i],message:'shot outside beat'});shotBeats.add(s.beat_id)});v.beats.forEach((b,i)=>{if(!shotBeats.has(b.beat_id))c.addIssue({code:'custom',path:['beats',i],message:'every beat needs a shot'});const t=b.primary_attention_target;if(t.target_id&&['evidence','owned_artifact','sketch','generated_illustration','screen'].includes(t.kind)&&!assets.has(t.target_id))c.addIssue({code:'custom',path:['beats',i,'primary_attention_target'],message:'unknown asset target'})})
 if(v.budget.estimated_cost_gbp>v.budget.maximum_cost_gbp)c.addIssue({code:'custom',path:['budget','estimated_cost_gbp'],message:'estimated cost exceeds maximum'});if(v.budget.maximum_cost_gbp>15&&!v.budget.exception_approved)c.addIssue({code:'custom',path:['budget','exception_approved'],message:'budgets above GBP 15 require approval'})
})
export type VisualNarrativePlanV1=z.infer<typeof VisualNarrativePlanV1Schema>

export const GeneratedShotV1Schema=z.object({schema_version:z.literal(1),generated_shot_id:IdentifierV1Schema,job_id:IdentifierV1Schema,provider:z.enum(['adobe_firefly','runway','google_veo','other']),model:z.string().min(1),model_version:z.string().min(1),prompt:z.string().min(12),uploaded_input_hashes:z.array(Sha256V1Schema).max(8),output_path:z.string().min(1),output_hash:Sha256V1Schema,width:z.number().int().positive(),height:z.number().int().positive(),duration_ms:z.number().int().positive(),cost_gbp:z.number().nonnegative(),truth_role:z.literal('illustration'),label:z.string().min(1),provenance:z.string().min(12),disclosure:z.array(DisclosureDecisionV1Schema).min(1),exact_approval:z.object({state:z.enum(['unreviewed','approved','rejected']),approved_by:z.literal('Krish').optional(),approved_at:z.string().min(1).optional(),output_hash:Sha256V1Schema.optional()}).strict()}).strict().superRefine((v,c)=>{if(Math.abs(v.width/v.height-9/16)>.02)c.addIssue({code:'custom',path:['width'],message:'generated shot must be portrait 9:16'});if(v.exact_approval.state==='approved'&&(v.exact_approval.output_hash!==v.output_hash||!v.exact_approval.approved_by||!v.exact_approval.approved_at))c.addIssue({code:'custom',path:['exact_approval'],message:'approval must bind exact output hash'})})
export type GeneratedShotV1=z.infer<typeof GeneratedShotV1Schema>

export const StyleframeV1Schema=z.object({frame_id:IdentifierV1Schema,beat_id:IdentifierV1Schema,at_ms:z.number().int().nonnegative(),image_path:z.string().min(1),image_hash:Sha256V1Schema,pixel_width:z.number().int().positive(),pixel_height:z.number().int().positive(),phone_preview_path:z.string().min(1),phone_preview_hash:Sha256V1Schema,asset_hashes:z.array(Sha256V1Schema),primary_attention_target:AttentionTargetV1Schema,legibility:z.object({passed:z.boolean(),notes:z.array(z.string().min(1))}).strict()}).strict()
const storyboardBase=z.object({schema_version:z.literal(1),packet_id:IdentifierV1Schema,job_id:IdentifierV1Schema,visual_plan_artifact_hash:Sha256V1Schema,created_at:z.string().min(1),exact_asset_hashes:z.array(Sha256V1Schema)})
export const StoryboardReviewPacketV1Schema=z.discriminatedUnion('review_kind',[storyboardBase.extend({review_kind:z.literal('styleframes'),styleframes:z.array(StyleframeV1Schema).min(3)}).strict(),storyboardBase.extend({review_kind:z.literal('animatic'),styleframes:z.array(StyleframeV1Schema).min(3),animatic:z.object({path:z.string().min(1),sha256:Sha256V1Schema,duration_ms:z.number().int().positive(),width:z.number().int().positive(),height:z.number().int().positive(),fps:z.number().positive(),includes_audio:z.boolean()}).strict()}).strict()]).superRefine((v,c)=>{if(!unique(v.styleframes.map(x=>x.frame_id)))c.addIssue({code:'custom',path:['styleframes'],message:'styleframe IDs must be unique'});v.styleframes.forEach((x,i)=>{if(x.pixel_width!==1080||x.pixel_height!==1920)c.addIssue({code:'custom',path:['styleframes',i],message:'styleframes must use 1080x1920 coordinates'})})})
export type StoryboardReviewPacketV1=z.infer<typeof StoryboardReviewPacketV1Schema>

export const PlatformSafeZonesV1Schema=z.object({top_px:z.number().int().nonnegative(),right_px:z.number().int().nonnegative(),bottom_px:z.number().int().nonnegative(),left_px:z.number().int().nonnegative()}).strict()
export const PlatformOutputV1Schema=z.object({platform:VideoPlatformV1Schema,width:z.literal(1080),height:z.literal(1920),fps:z.literal(30),audio_hz:z.literal(48000),safe_zones:PlatformSafeZonesV1Schema,maximum_duration_ms:z.number().int().positive()}).strict().superRefine((v,c)=>{if(v.safe_zones.left_px+v.safe_zones.right_px>=v.width)c.addIssue({code:'custom',path:['safe_zones'],message:'horizontal safe zones consume frame'});if(v.safe_zones.top_px+v.safe_zones.bottom_px>=v.height)c.addIssue({code:'custom',path:['safe_zones'],message:'vertical safe zones consume frame'})})
export const CaptionCueV2Schema=z.object({start_ms:z.number().int().nonnegative(),end_ms:z.number().int().positive(),text:z.string().min(1),emphasis:z.array(z.string()).default([])}).strict().refine(v=>v.end_ms>v.start_ms,{message:'caption must end after start'})
export const DialogueEditV1Schema=z.object({edit_id:IdentifierV1Schema,source_id:IdentifierV1Schema,output_start_ms:z.number().int().nonnegative(),output_end_ms:z.number().int().positive(),source_start_ms:z.number().int().nonnegative(),source_end_ms:z.number().int().positive(),gain_db:z.number().max(0),fade_in_ms:z.number().int().nonnegative(),fade_out_ms:z.number().int().nonnegative()}).strict().superRefine((v,c)=>{if(v.output_end_ms<=v.output_start_ms)c.addIssue({code:'custom',path:['output_end_ms'],message:'dialogue edit must end after it starts'});if(v.source_end_ms<=v.source_start_ms)c.addIssue({code:'custom',path:['source_end_ms'],message:'dialogue source span must end after it starts'});const outputDuration=v.output_end_ms-v.output_start_ms,sourceDuration=v.source_end_ms-v.source_start_ms;if(Math.abs(outputDuration-sourceDuration)>34)c.addIssue({code:'custom',path:['source_end_ms'],message:'dialogue source and output durations must match within one frame'});if(v.fade_in_ms+v.fade_out_ms>outputDuration)c.addIssue({code:'custom',path:['fade_out_ms'],message:'dialogue fades cannot exceed edit duration'})})
export const AudioPlanV1Schema=z.object({dialogue_source_ids:z.array(IdentifierV1Schema).min(1),dialogue_master_source_id:IdentifierV1Schema,dialogue_edits:z.array(DialogueEditV1Schema).min(1),transitions:z.array(z.object({at_ms:z.number().int().nonnegative(),kind:z.enum(['crossfade','j_cut','l_cut','room_tone','sound_bridge']),duration_ms:z.number().int().positive()}).strict()),music:z.array(z.object({asset_id:IdentifierV1Schema,start_ms:z.number().int().nonnegative(),end_ms:z.number().int().positive(),gain_db:z.number().max(0),rights:z.string().min(1)}).strict()),effects:z.array(z.object({asset_id:IdentifierV1Schema,at_ms:z.number().int().nonnegative(),gain_db:z.number().max(0),purpose:z.string().min(8),rights:z.string().min(1)}).strict()),target_lufs:z.literal(-14),maximum_true_peak_dbtp:z.literal(-1)}).strict().superRefine((v,c)=>{
  if(!v.dialogue_source_ids.includes(v.dialogue_master_source_id))c.addIssue({code:'custom',path:['dialogue_master_source_id'],message:'dialogue master must be a dialogue source'})
  if(!unique(v.dialogue_source_ids))c.addIssue({code:'custom',path:['dialogue_source_ids'],message:'dialogue source IDs must be unique'})
  if(!unique(v.dialogue_edits.map(x=>x.edit_id)))c.addIssue({code:'custom',path:['dialogue_edits'],message:'dialogue edit IDs must be unique'})
  v.dialogue_edits.forEach((x,i)=>{if(!v.dialogue_source_ids.includes(x.source_id))c.addIssue({code:'custom',path:['dialogue_edits',i,'source_id'],message:'dialogue edit source must be declared'})})
  if(v.transitions.length)c.addIssue({code:'custom',path:['transitions'],message:'audio transition metadata is not implemented; use contiguous direct dialogue edits'})
  if(v.music.length)c.addIssue({code:'custom',path:['music'],message:'music is blocked until a governed approved audio-asset ledger exists'})
  if(v.effects.length)c.addIssue({code:'custom',path:['effects'],message:'sound effects are blocked until a governed approved audio-asset ledger exists'})
})
const RenderSourceV2BaseSchema=z.object({source_id:IdentifierV1Schema,path:z.string().min(1),sha256:Sha256V1Schema,duration_ms:z.number().int().positive(),canonical_offset_ms:z.number().int()})
export const VisualRenderSourceV2Schema=RenderSourceV2BaseSchema.extend({kind:z.enum(['video','screen_recording']),width:z.number().int().positive(),height:z.number().int().positive(),fps:z.number().positive(),audio_hz:z.number().int().positive().nullable()}).strict()
export const AudioOnlyRenderSourceV2Schema=RenderSourceV2BaseSchema.extend({kind:z.literal('audio'),width:z.null(),height:z.null(),fps:z.null(),audio_hz:z.number().int().positive()}).strict()
export const RenderSourceV2Schema=z.union([VisualRenderSourceV2Schema,AudioOnlyRenderSourceV2Schema])
export const RenderManifestV2Schema=z.object({schema_version:z.literal(2),manifest_id:IdentifierV1Schema,job_id:IdentifierV1Schema,candidate_id:IdentifierV1Schema,candidate_hash:Sha256V1Schema,visual_plan_artifact_hash:Sha256V1Schema,storyboard_artifact_hash:Sha256V1Schema.optional(),series:SeriesV2Schema,treatment_id:IdentifierV1Schema,treatment_lane:TreatmentLaneV1Schema,target_platform:VideoPlatformV1Schema,output:PlatformOutputV1Schema,duration_ms:z.number().int().positive(),sources:z.array(RenderSourceV2Schema).min(1).max(32),shot_directives:z.array(ShotDirectiveV1Schema).min(1),assets:z.array(VisualAssetV1Schema),generated_shots:z.array(GeneratedShotV1Schema),captions:z.array(CaptionCueV2Schema),caption_provenance:z.object({transcript_hash:Sha256V1Schema,verified:z.literal(true),exact_word_fidelity:z.literal(true),source_token_count:z.number().int().nonnegative(),caption_token_count:z.number().int().nonnegative()}).strict(),audio_plan:AudioPlanV1Schema,branding:z.object({mode:z.enum(['series','none']),theme_id:IdentifierV1Schema.optional(),theme_version:z.number().int().positive().optional(),theme_hash:Sha256V1Schema.optional(),wordmark_hashes:z.array(Sha256V1Schema).default([])}).strict(),disclosures:z.array(DisclosureDecisionV1Schema),fixed_seed:z.string().min(16)}).strict().superRefine((v,c)=>{
 if(v.output.platform!==v.target_platform)c.addIssue({code:'custom',path:['output','platform'],message:'output platform must match render target'})
 if(v.duration_ms>v.output.maximum_duration_ms)c.addIssue({code:'custom',path:['duration_ms'],message:'render exceeds platform duration'})
 const sources=v.sources.map(x=>x.source_id)
 if(!unique(sources))c.addIssue({code:'custom',path:['sources'],message:'source IDs must be unique'})
 const sourceSet=new Set(sources),sourceMap=new Map(v.sources.map(x=>[x.source_id,x]))
 v.shot_directives.forEach((x,i)=>{
   if(!sourceSet.has(x.source_id))c.addIssue({code:'custom',path:['shot_directives',i,'source_id'],message:'unknown render source'})
   if(x.end_ms>v.duration_ms)c.addIssue({code:'custom',path:['shot_directives',i,'end_ms'],message:'shot exceeds duration'})
   if(x.audio_continuity!=='direct')c.addIssue({code:'custom',path:['shot_directives',i,'audio_continuity'],message:'non-direct shot audio continuity is not implemented; use direct'})
   const source=sourceMap.get(x.source_id)
   if(source?.kind==='audio')c.addIssue({code:'custom',path:['shot_directives',i,'source_id'],message:'shot source must contain video'})
   if(source&&x.source_end_ms>source.duration_ms)c.addIssue({code:'custom',path:['shot_directives',i,'source_end_ms'],message:'shot exceeds source duration'})
   x.layers.forEach((layer,layerIndex)=>{const layerSource=layer.kind==='source'&&layer.target_id?sourceMap.get(layer.target_id):undefined;if(layerSource?.kind==='audio')c.addIssue({code:'custom',path:['shot_directives',i,'layers',layerIndex,'target_id'],message:'visual source layers cannot reference an audio-only source'})})
 })
 v.audio_plan.dialogue_source_ids.forEach((sourceId,i)=>{const source=sourceMap.get(sourceId);if(!source)c.addIssue({code:'custom',path:['audio_plan','dialogue_source_ids',i],message:'unknown dialogue source'});else if(!source.audio_hz)c.addIssue({code:'custom',path:['audio_plan','dialogue_source_ids',i],message:'dialogue source has no audio'})})
 const sortedDialogue=v.audio_plan.dialogue_edits.map((edit,index)=>({edit,index})).sort((left,right)=>left.edit.output_start_ms-right.edit.output_start_ms||left.edit.output_end_ms-right.edit.output_end_ms)
 let dialogueCoveredUntil=0
 sortedDialogue.forEach(({edit,index})=>{
   const source=sourceMap.get(edit.source_id)
   if(!source)c.addIssue({code:'custom',path:['audio_plan','dialogue_edits',index,'source_id'],message:'unknown dialogue source'})
   else{if(!source.audio_hz)c.addIssue({code:'custom',path:['audio_plan','dialogue_edits',index,'source_id'],message:'dialogue source has no audio'});if(edit.source_end_ms>source.duration_ms)c.addIssue({code:'custom',path:['audio_plan','dialogue_edits',index,'source_end_ms'],message:'dialogue edit exceeds source duration'})}
   if(edit.output_end_ms>v.duration_ms)c.addIssue({code:'custom',path:['audio_plan','dialogue_edits',index,'output_end_ms'],message:'dialogue edit exceeds render duration'})
   if(edit.output_start_ms<dialogueCoveredUntil)c.addIssue({code:'custom',path:['audio_plan','dialogue_edits',index,'output_start_ms'],message:`dialogue timeline overlaps from ${edit.output_start_ms} ms to ${dialogueCoveredUntil} ms`})
   else if(edit.output_start_ms>dialogueCoveredUntil)c.addIssue({code:'custom',path:['audio_plan','dialogue_edits',index,'output_start_ms'],message:`dialogue timeline has a gap from ${dialogueCoveredUntil} ms to ${edit.output_start_ms} ms`})
   dialogueCoveredUntil=Math.max(dialogueCoveredUntil,edit.output_end_ms)
 })
 if(dialogueCoveredUntil<v.duration_ms)c.addIssue({code:'custom',path:['audio_plan','dialogue_edits'],message:`dialogue timeline ends at ${dialogueCoveredUntil} ms before render duration ${v.duration_ms} ms`})
 v.captions.forEach((x,i)=>{if(x.end_ms>v.duration_ms)c.addIssue({code:'custom',path:['captions',i,'end_ms'],message:'caption exceeds duration'})})
 const assetHashes=new Set(v.assets.map(x=>x.sha256));v.generated_shots.forEach((x,i)=>{if(!assetHashes.has(x.output_hash))c.addIssue({code:'custom',path:['generated_shots',i,'output_hash'],message:'generated output missing from exact asset ledger'})})
})
export type RenderManifestV2=z.infer<typeof RenderManifestV2Schema>

export const DraftPackageV2Schema=z.object({schema_version:z.literal(2),package_id:IdentifierV1Schema,job_id:IdentifierV1Schema,platform:VideoPlatformV1Schema,render_manifest_hash:Sha256V1Schema,master_path:z.string().min(1),master_hash:Sha256V1Schema,captions_path:z.string().min(1),captions_hash:Sha256V1Schema,cover_path:z.string().min(1),cover_hash:Sha256V1Schema,platform_metadata_path:z.string().min(1),platform_metadata_hash:Sha256V1Schema,titles_path:z.string().min(1),titles_hash:Sha256V1Schema,post_path:z.string().min(1),post_hash:Sha256V1Schema,titles:z.array(z.string().min(1)).min(1),description:z.string(),post_copy:z.string(),pinned_comment:z.string().optional(),claim_ledger_path:z.string().min(1),claim_ledger_hash:Sha256V1Schema,asset_ledger_path:z.string().min(1),asset_ledger_hash:Sha256V1Schema,provenance_path:z.string().min(1),provenance_hash:Sha256V1Schema,disclosure:DisclosureDecisionV1Schema,delivery:z.object({mode:z.enum(['private_upload','local_package']),privacy:z.enum(['private','not_applicable']),public_publish_allowed:z.literal(false)}).strict(),created_at:z.string().min(1)}).strict().superRefine((v,c)=>{if(v.disclosure.platform!==v.platform)c.addIssue({code:'custom',path:['disclosure','platform'],message:'disclosure platform mismatch'});if(v.platform!=='youtube_shorts'&&v.delivery.mode!=='local_package')c.addIssue({code:'custom',path:['delivery','mode'],message:'only YouTube may be privately uploaded'});if(v.delivery.mode==='private_upload'&&v.delivery.privacy!=='private')c.addIssue({code:'custom',path:['delivery','privacy'],message:'uploads must be private'});if(v.delivery.mode==='local_package'&&v.delivery.privacy!=='not_applicable')c.addIssue({code:'custom',path:['delivery','privacy'],message:'local package privacy is not applicable'})})
export type DraftPackageV2=z.infer<typeof DraftPackageV2Schema>

export const EditorialEvidencePacketRefV1Schema=z.object({packet_path:z.string().min(1),packet_hash:Sha256V1Schema,contact_sheet_path:z.string().min(1),contact_sheet_hash:Sha256V1Schema}).strict()
export const AssetsStagePayloadV2Schema=z.object({visual_plan_artifact_hash:Sha256V1Schema,assets:z.array(VisualAssetV1Schema),generated_shots:z.array(GeneratedShotV1Schema),editorial_evidence:EditorialEvidencePacketRefV1Schema.optional()}).strict()
export const TreatmentStagePayloadV2Schema=z.object({manifests:z.array(z.object({platform:VideoPlatformV1Schema,manifest_path:z.string().min(1),manifest_hash:Sha256V1Schema}).strict()).min(1)}).strict()
export type TreatmentStagePayloadV2=z.infer<typeof TreatmentStagePayloadV2Schema>
export const RenderStagePayloadV2Schema=z.object({renders:z.array(z.object({platform:VideoPlatformV1Schema,master_path:z.string().min(1),master_hash:Sha256V1Schema,manifest_path:z.string().min(1),manifest_hash:Sha256V1Schema}).strict()).min(1)}).strict()
export const PackageStagePayloadV2Schema=z.object({packages:z.array(DraftPackageV2Schema).min(1)}).strict()
export const StageArtifactV2BaseSchema=z.object({schema_version:z.literal(2),job_id:IdentifierV1Schema,stage:StageNameV2Schema,created_at:z.string().min(1),input_hashes:z.record(z.string(),Sha256V1Schema),config_hash:Sha256V1Schema,tool_versions:z.record(z.string(),z.string().min(1)),payload:z.unknown(),artifact_hash:Sha256V1Schema}).strict()
export const StageArtifactV2Schema=StageArtifactV2BaseSchema.superRefine((v,c)=>{const schemas:Partial<Record<StageNameV2,z.ZodType>>={source_analysis:SourceVisualAnalysisV1Schema,visual_plan:VisualNarrativePlanV1Schema,assets:AssetsStagePayloadV2Schema,styleframes:StoryboardReviewPacketV1Schema,animatic:StoryboardReviewPacketV1Schema,treatment:TreatmentStagePayloadV2Schema,render:RenderStagePayloadV2Schema,package:PackageStagePayloadV2Schema};const parsed=schemas[v.stage]?.safeParse(v.payload);if(parsed&&!parsed.success)parsed.error.issues.forEach(i=>c.addIssue({code:'custom',path:['payload',...i.path],message:i.message}));if(parsed?.success&&v.stage==='styleframes'&&(parsed.data as {review_kind?:string}).review_kind!=='styleframes')c.addIssue({code:'custom',path:['payload','review_kind'],message:'styleframes stage requires styleframes packet'});if(parsed?.success&&v.stage==='animatic'&&(parsed.data as {review_kind?:string}).review_kind!=='animatic')c.addIssue({code:'custom',path:['payload','review_kind'],message:'animatic stage requires animatic packet'})})
export type StageArtifactV2=z.infer<typeof StageArtifactV2Schema>

const PercentageV2Schema = z.number().min(0).max(100).nullable()
const NonnegativeRateV2Schema = z.number().nonnegative().nullable()
const NormalizedQualityV2Schema = z.number().min(0).max(1).nullable()
const AnalyticsMetricsV2Schema = z.object({
  impressions:z.number().nonnegative().nullable(), views:z.number().nonnegative().nullable(), viewed_vs_swiped:PercentageV2Schema, early_hold_rate:PercentageV2Schema, average_view_duration_seconds:z.number().nonnegative().nullable(), average_percentage_viewed:NonnegativeRateV2Schema, completion_rate:PercentageV2Schema, rewatch_rate:NonnegativeRateV2Schema, shares:z.number().nonnegative().nullable(), saves:z.number().nonnegative().nullable(), comments:z.number().nonnegative().nullable(), substantive_comments:z.number().nonnegative().nullable(), comment_quality:NormalizedQualityV2Schema, followers_gained:z.number().nonnegative().nullable(), qualified_actions:z.number().nonnegative().nullable(), utm_actions:z.number().nonnegative().nullable(),
}).strict()
export const AnalyticsObservationV2Schema = AnalyticsMetricsV2Schema.extend({ schema_version:z.literal(2), observation_id:z.string().uuid(), job_id:IdentifierV1Schema, platform:VideoPlatformV1Schema, published_at:z.string().optional(), published_artifact_hash:Sha256V1Schema, source_file_hash:Sha256V1Schema }).strict()
export type AnalyticsObservationV2 = z.infer<typeof AnalyticsObservationV2Schema>
export const ExperimentV2Schema = z.object({ schema_version:z.literal(2), experiment_id:z.string().uuid(), hypothesis:z.string().min(12), primary_variable:z.string().min(1), control_job_ids:z.array(IdentifierV1Schema).min(1), treatment_job_ids:z.array(IdentifierV1Schema).min(1), platform:VideoPlatformV1Schema, target_metric:z.string().min(1), editorial_guard_metrics:z.array(z.enum(['semantic_coherence','impact','relevance','insight','specificity','audience_value','hook_strength','ending_strength'])).min(1), qualified_guard_metric:z.enum(['qualified_actions','utm_actions','followers_gained']), confounds:z.array(z.string()), status:z.enum(['planned','running','eligible','approved','rejected']) }).strict().superRefine((v,c)=>{
  if(new Set(v.control_job_ids).size!==v.control_job_ids.length)c.addIssue({code:'custom',path:['control_job_ids'],message:'control jobs must be unique'})
  if(new Set(v.treatment_job_ids).size!==v.treatment_job_ids.length)c.addIssue({code:'custom',path:['treatment_job_ids'],message:'treatment jobs must be unique'})
  const control=new Set(v.control_job_ids);if(v.treatment_job_ids.some(id=>control.has(id)))c.addIssue({code:'custom',path:['treatment_job_ids'],message:'control and treatment jobs must be disjoint'})
  if(v.control_job_ids.length!==v.treatment_job_ids.length)c.addIssue({code:'custom',path:['treatment_job_ids'],message:'control and treatment jobs must form equal ordered pairs'})
})
export type ExperimentV2 = z.infer<typeof ExperimentV2Schema>

export const ConfigChangeProposalV1Schema = z.object({ schema_version:z.literal(1), proposal_id:IdentifierV1Schema, rule_id:z.string().min(1), from_status:z.enum(['eligible','user_approved']), requested_status:z.literal('active'), base_config_path:z.string().min(1), base_config_hash:Sha256V1Schema, proposed_at:z.string().min(1), proposed_by:z.literal('Krish'), patch:z.object({ operation:z.literal('append_active_preference'), value:z.unknown() }).strict(), proposal_hash:Sha256V1Schema, activation_boundary:z.literal('reviewed_git_commit') }).strict()
export type ConfigChangeProposalV1 = z.infer<typeof ConfigChangeProposalV1Schema>
